//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCatalog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Autos
    {
        [HiddenInput(DisplayValue = false)]
        public int ID { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int UserID { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int MakeID { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int ModeLID { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int ColorID { get; set; }
        [Display(Name = "Номер машины")]
        public string RegistryNum { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Makes Makes { get; set; }
        public virtual Users Users { get; set; }
        public virtual CarModels CarModels { get; set; }
    }
}
